# Generated by Django 4.2.16 on 2024-11-19 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sso_gateway", "0002_alter_authenticationrequest_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
    ]
